spring.config.import=optional:secrets.properties
spring.application.name=boursieres

#actions.api-url=http:localhost:8080/actions
#actions.api-version=2025-02-12

spring.datasource.url=${actions.database-url}
spring.datasource.username=${actions.database-username}
spring.datasource.password=${actions.database-password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

#Alpha
alpha_vantage.api.key=${actions.api-vantage-key}
alpha_vantage.api.url=${actions.api-vantage-url}
stock.update.frequency=60000
